use_weighted_masking: false
mask_rate: 0.3
cdr_weight_multiplier: 1.0
nongermline_weight_multiplier: 1.0
v_weight_multiplier: 0.0
d_weight_multiplier: 0.0
j_weight_multiplier: 0.0
n_weight_multiplier: 0.0
selection_method: sampled
